//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstIteration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int SLID { get; set; }
        public int Year { get; set; }
        public int State { get; set; }
        public int Medicaid { get; set; }
        public int Commercial { get; set; }
    }
}
